"""
Charge Sheet Service - Skill 06
Automates the creation of the Final Report under BNSS using OpenAI
"""
import uuid
import json
import openai
from datetime import datetime
from typing import List, Optional, Dict
from app.core.config import settings
from app.schemas.chargesheet import (
    ChargeSheet, ChargeSheetCreate, ChargeSheetUpdate,
    ChargeSheetStatus, AccusedDetails, OffenseSection,
    WitnessSummary, EvidenceSummary
)
from app.services.police.smart_fir import get_smart_fir_service

class ChargeSheetService:
    """
    Generates and manages charge sheets
    """
    
    def __init__(self):
        self.repository: Dict[str, ChargeSheet] = {}
        api_key = settings.OPENAI_API_KEY
        if not api_key:
            print("WARNING: OPENAI_API_KEY not set. Charge Sheet generation will fail.")
        self.client = openai.OpenAI(api_key=api_key)
        
    async def generate_draft(self, fir_id: str, user: dict) -> ChargeSheet:
        """
        Auto-generate a draft charge sheet from FIR and investigation data using AI
        """
        # 1. Fetch FIR Data
        fir_service = get_smart_fir_service()
        fir = await fir_service.get_fir(fir_id)
        
        fir_context = ""
        if fir:
            fir_context = f"""
            FIR ID: {fir.fir_number}
            Complaint: {fir.complaint_text}
            Analysis: {fir.analysis}
            """
        else:
            fir_context = f"FIR ID: {fir_id} (Details not found, generate generic template)"

        # 2. Generate content via OpenAI
        try:
            system_prompt = """You are an expert Public Prosecutor and Police IO. 
            Draft a Charge Sheet (Final Report) under BNSS based on the provided FIR context.
            
            Output valid JSON with:
            - offenses: List of {act, section, description, is_bailable (bool), max_punishment}
            - brief_facts: Summary of the incident and case history.
            - investigation_details: Detailed steps taken (CCTV collected, witnesses examined, etc).
            - accused: List of {name, parentage, address, is_arrested (bool), remand_status} (Infer or create placeholders).
            - witnesses: List of {name, statement_summary, is_key_witness (bool)}.
            - evidence_list: List of {description, seizure_memo_ref}.
            """
            
            completion = self.client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Context:\n{fir_context}"}
                ],
                response_format={"type": "json_object"},
                temperature=0.3
            )
            
            data = json.loads(completion.choices[0].message.content)
            
            # Map JSON to Objects
            offenses = [OffenseSection(**o) for o in data.get("offenses", [])]
            accused = [
                AccusedDetails(
                    id=str(uuid.uuid4()),
                    arrest_date=datetime.now() if a.get("is_arrested") else None,
                    **a
                ) for a in data.get("accused", [])
            ]
            witnesses = [WitnessSummary(id=str(uuid.uuid4()), **w) for w in data.get("witnesses", [])]
            evidence_list = [EvidenceSummary(id=str(uuid.uuid4()), **e) for e in data.get("evidence_list", [])]
            
            brief_facts = data.get("brief_facts", "Generated by AI")
            investigation_details = data.get("investigation_details", "Investigation pending.")

        except Exception as e:
            print(f"AI Generation Failed: {e}")
            # Fallback
            offenses = []
            accused = []
            witnesses = []
            evidence_list = []
            brief_facts = "Draft generation failed. Please fill manually."
            investigation_details = str(e)

        draft_id = str(uuid.uuid4())
        
        draft = ChargeSheet(
            id=draft_id,
            fir_id=fir_id,
            police_station="PS Sector 4", # Mock defaults
            district="Cyber City",
            year=datetime.now().year,
            complainant_name=fir.complainant_name if fir else "Unknown",
            accused=accused,
            offenses=offenses,
            brief_facts=brief_facts,
            investigation_details=investigation_details,
            witnesses=witnesses,
            evidence_list=evidence_list,
            investigating_officer=user.get("full_name", "Unknown IO"),
            status=ChargeSheetStatus.DRAFT,
            created_at=datetime.now(),
            updated_at=datetime.now()
        )
        
        self.repository[draft_id] = draft
        return draft

    async def get_chargesheet(self, cs_id: str) -> Optional[ChargeSheet]:
        return self.repository.get(cs_id)

    async def update_chargesheet(self, cs_id: str, update_data: ChargeSheetUpdate) -> Optional[ChargeSheet]:
        cs = self.repository.get(cs_id)
        if not cs:
            return None
            
        # Update fields if provided
        if update_data.brief_facts:
            cs.brief_facts = update_data.brief_facts
        if update_data.investigation_details:
            cs.investigation_details = update_data.investigation_details
        if update_data.status:
            cs.status = update_data.status
        if update_data.offenses:
            cs.offenses = update_data.offenses
        if update_data.accused:
            cs.accused = update_data.accused
            
        cs.updated_at = datetime.now()
        return cs


# Singleton
chargesheet_service = ChargeSheetService()
